SrReg1:
    comment: empty
    id: 1
    is_valid: false
    value: empty
SrReg10:
    comment: empty
    id: 10
    is_valid: false
    value: empty
SrReg2:
    comment: empty 
    id: 2
    is_valid: false
    value: empty
SrReg3:
    comment: empty
    id: 3
    is_valid: false
    value: empty
SrReg4:
    comment: empty
    id: 4
    is_valid: false
    value: empty
SrReg5:
    comment: empty
    id: 5
    is_valid: false
    value: empty
SrReg6:
    comment: empty
    id: 6
    is_valid: false
    value: empty
SrReg7:
    comment: empty
    id: 7
    is_valid: false
    value: empty
SrReg8:
    comment: empty
    id: 8
    is_valid: false
    value: empty
SrReg9:
    comment: empty
    id: 9
    is_valid: false
    value: empty

#END
